# Generated by Django 6.1.1 on 2026-09-08 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('ST', 'Student'), ('IN', 'Instructor'), ('AD', 'Admin')], max_length=100)),
                ('department', models.CharField(choices=[('IT', 'Information Technology'), ('CS', 'Computer Science')], max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('student_id', models.IntegerField(blank=True, max_length=100, null=True)),
                ('employee_id', models.IntegerField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
