# Generated by Django 6.1.1 on 2026-09-16 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_instructor_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationslot',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'IN'}, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_level',
            field=models.CharField(blank=True, choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=30, null=True),
        ),
    ]
