# Generated by Django 6.1.1 on 2026-10-05 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_consultationbooking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_student_appointment_per_slot',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='appointment',
        ),
        migrations.RemoveConstraint(
            model_name='consultationbooking',
            name='unique_slot_student_booking',
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.consultationbooking'),
        ),
        migrations.AlterField(
            model_name='consultationbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO SHOW', 'No Show')], default='PENDING', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='consultationbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CANCELLED', 'REJECTED'])), fields=('slot', 'student'), name='unique_slot_student_booking'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
